spring.profiles.active: local
spring.r2dbc:
  url: r2dbc:mysql://localhost:3306/testdb?characterEncoding=UTF-8&useSSL=false
  username: test
  password: test

server:
  port: 8080

armeria:
  ports:
    - port: 8080
      protocol: http

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,prometheus,env,info,configprops,mappings,conditions,beans,loggers,caches
