spring.profiles.active: local
server:
  port: 8080

armeria:
  ports:
    - port: 8080
      protocol: http

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health,prometheus,env,info,configprops,mappings,conditions,beans,loggers,caches